language: node_js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  global:
    # github
    - secure: "fb+ntbBEea+t+viORaWUbBkelRGGBLh7E+C19PFtJygdJ0qPTHEsMCs2137qW4rp2QtsYlZrdPccaH6aWYQF2TrvMNIAAmhhMAn8ySdljEf/QOpjJa87ETffajRiw0D+k4pD4/hRoX/4sZKnqt15TQ5zj68KfWHImQrtKqi/1vecUtBLqAOs21Uo+1ZgJgb0JfiTItl7/iudFHmX255Kb2uva1YlwIg2MWqIUesnMROMDhOYp1vbnJlcj4kufEMKZVkV3zxVmfBfKFXnrT9ygGAwTXimMionzI0hr8GqS8qDNSWCyaC6vVDcBydZR8MIMEdmPZwaD9Uh9vyw5eKRPaEj/jOksGzyluom3gbB+hL+eoSppx6uBGATb/W1RP59Z6B1ScOKjCiNAL2A6FvMD/yy1HQVMHoZfdvUpEhuG2wnlXbIYfybXbZ1r7O2ARAnAJffjn5hqPPGa7O7cbFxo/oaeIcqAU7H/O4aITJ7GKQarBTLj8OO6NfswE8eoVaBglmuyfwk5mNiZesBow3gde65HhCjdYS4eTVqNdmbNZT8eXnaD7cMeUvv8dxey1cQbOAYvI2NlvmM0GpZVEChMXP+gr/bgfrKIS45lh5+Z8/yCCjqjTS/9Zr1D7Qn0ahbuxm2zDhChLcCgvcY7RLebSB8xd8pX9i1UQcf/4l+FrM="
    # npm
    - secure: "FcOI65Ojfn5PzB+OdDzYig1gn3omHcmqNzytAex6t0cmMZZ1f4vzbRYEJcHT0JZ3t20WKpf1O69/g1CvUp9ljpahiveemcjDGrmfofeuJTuebVm7LReEqdYAn0R5Z+HZHC1nt3eIgCwnIACw78V4HQEAkkLcVq3NJgFEq63CDhUqBm0IS86VComaO5x9H31PrQK8fQum6/g+cXcgfaOtGKkOhnesXfrQs6nzjZ4Pf/3/PC/68ldvd+YTjy87Vbb90ciHSw42DlXokjmUPOcPwxgDu+9Kr9lbIOWMy1x88xoHpo5e/lCh8+kHUXPAyhZb8lbI2HhrpyfZd8H57IUZSfA6ohmsY2bcby+M7rxRnmQrV2pF1TW08yThWQhj93Duu3VAXXmlp1g+KKb/EK3WkE5q4Pqks9pbXFYNpJunhXgZv06Ez7zQUsSnTVFBHj8rct0aM/eZugO5hdbbuxF0CYxgjnltCGLznaDVzchEjb/qTInrLck2V/HZ1pYVqxJjFmPX9tsKSy3HXNzQ1LmnSceB8Fj+JqP/vOoR6IMOylpkQ/iKPsgxejW8oHlBwQOFfZH2rrpH4C7mS0cKO0/de0dCimefJwHsDplLRVnlCbi0rCpey1qChzvsrzRqIlHioXdUCDvT0k8P+bnfTsOPa6tV2i11hlXG6Mk+EF+jPt0="
cache:
  npm: true
  directories:
    - dist
    - reports
jobs:
  include:
    - stage: prepare cache
      name: install
      before_install:
        - rm -rf dist reports
      install:
        - npm i
    - stage: website
      name: build
      script:
        # - echo $TRAVIS_PULL_REQUEST_BRANCH
        # - echo $TRAVIS_BRANCH
        # - echo $TRAVIS_COMMIT
        # - echo $TRAVIS_PULL_REQUEST_SHA
        - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then export PT_BRANCH=$TRAVIS_BRANCH; else export PT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi
        - if [ -z "$TRAVIS_PULL_REQUEST_SHA" ]; then export PT_COMMIT=$TRAVIS_COMMIT; else export PT_COMMIT=$TRAVIS_PULL_REQUEST_SHA; fi
        # - echo $PT_COMMIT
        # - echo $PT_BRANCH
        - npm run static --base=/nuxt-page-generator-helper/
    - stage: deploy
      if: branch = master
      install:
        - npm i semantic-release @semantic-release/exec @semantic-release/git @semantic-release/changelog --no-save
      script:
        - npx semantic-release --provider=github
        - mkdir gh-pages gh-pages/reports
        - cp -R dist/* gh-pages/
        - cp -R reports/* gh-pages/reports/
        - touch gh-pages/.nojekyll
      deploy:
        provider: pages
        cleanup: false
        github_token: $GITHUB_TOKEN
        local_dir: gh-pages/
        on:
          branch: master
        edge: true

