language: node_js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  global:
    # github
    - secure: "cWoEtZUppxyoQ6FIoyKZpm6QgichsshlOKVPRm0h2jtME8iZtDrbavZ+6697ARPqBOskNVOsfWht9U2LoIHSJE+9ZckKaqB+GF2HkuwUbiVRDa/YRVjjYt6MJnyeEZMV4kN7Fri+twhykWtp7yDU0tKFkLhel+vJr9Y1rlLVbhf/t60fMjjKfk00f9G/xxsIC+2+wzEoScoik1ZS2zaiNuLT5YxBj+5OvUHV/29JwOwpOUh1HHqeSFNNGFBOgr9OgAglPRrxRdeTa77IRvj2zieilt464IHDd6+T6NMPFbGc7rwRZLbF36O6sAH7OufqZNT01mSkXjk7OFtefI3pC5fQRqa3K0/88bl6Z64/A++gVyG566m6y6UYx05s8aBuB5dlRMCd1oGGHksoMKkqrUQO3TRtS2Smo51sRdsr6VPYAW1NjsPTEEYrdqoyJM5S0VB0gwccYgHmWbT1PEOwGjLcfNNyZq7r8/v1JrPhgHx4M4XvzJlR63GWhqeMTnfkk/XGIalvrymTV6Y9cHyWjziZk6gkaug8iM17/j0ISso3stmGYtfTnXrvYIkQ0nPMXhUfc0EKy+cXYyS3UeTP1yzxSdcVtFS9v6dnpV2kx3NLM7NkYac0dKsoqftiii2zqDMr2Gek7K3CMCAVdlC0fB1yuqYDt4GQfRg9vPcbtAw="
    #npm
    - secure: "Odw3LylqBzd7sclTpi+NGjwF9UNGU/ViJfK9elbZwpdsZfWO+l/Ito+VNyRlTiMGjinbntmDsXvw54fhCI4rjdEePvsfFUMOPikY2HiAvGmtCtWqUGDvNlsJ9UFvvo3FuigFve5ZVnXLj518hDtROk/bla9sQFUO7UWoC2dfgTMK3XB8VMtRqcqjENq5Y9VLFOlm2XVPc5Hri56btknVW4Rr+R5YVK2JHy9XtczWxZckOJqcfeEB6NXh0gjw3LKi7Vv28Tsin88PAdr/DviG8eNu3MBKV36cmnFNL3qils5ykHjJq6FIAy7Xmpxoxsqlt8CLK4sJHGn4rj/Wx5UfIcta4M3WdzW8CE0xdbCklkd/lZtoGaCs2a83KEFudCW8VEcRTAcv7giIOulaKn9e6TX8E3PoKVv4whMZrdbQVO1jEUn50srF/jQhc5OyP3V3d9IXXob6A74rinXMlcQLz/zm+M8Ck/tuzV4nni6PSO8+5a19MV1z/XJ+LZHrp7oEe99M2aVbaLtBCzCH5XSjh/N0QohFG3B/+xsQwzpj5ZGRmJseOTJtqOvI7LfflIHiboh1nVq5GogUDg+IKWB/EkLqxToxra0S29q8r+a6tjoHLWr63XdQjOheTBuFME2BYgUK6zvP6qcqbZ/q8P8d5xKCAa7OxM2zv8/YjOM+Ly8="
cache:
  npm: true
  directories:
    - dist
    - reports
jobs:
  include:
    - stage: prepare cache
      name: install
      before_install:
        - rm -rf dist reports
      install:
        - npm i
    - stage: website
      name: build
      script:
        # - echo $TRAVIS_PULL_REQUEST_BRANCH
        # - echo $TRAVIS_BRANCH
        # - echo $TRAVIS_COMMIT
        # - echo $TRAVIS_PULL_REQUEST_SHA
        - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then export PT_BRANCH=$TRAVIS_BRANCH; else export PT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi
        - if [ -z "$TRAVIS_PULL_REQUEST_SHA" ]; then export PT_COMMIT=$TRAVIS_COMMIT; else export PT_COMMIT=$TRAVIS_PULL_REQUEST_SHA; fi
        # - echo $PT_COMMIT
        # - echo $PT_BRANCH
        - npm run static --base=/nuxt-page-generator-helper/
    - stage: deploy
      if: branch = master
      install:
        - npm i semantic-release @semantic-release/exec @semantic-release/git @semantic-release/changelog --no-save
      script:
        - npx semantic-release --provider=github
        - mkdir gh-pages gh-pages/reports
        - cp -R dist/* gh-pages/
        - cp -R reports/* gh-pages/reports/
        - touch gh-pages/.nojekyll
      deploy:
        provider: pages
        cleanup: false
        github_token: $GITHUB_TOKEN
        local_dir: gh-pages/
        on:
          branch: master
        edge: true

