language: node_js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  global:
    # github
    - secure: bAR6lRkIKyNOXQcqg4VzbiWuw9KF/Idok3nH6yO7NsOnRuRvdnJYWIfDr74x5kKLyMYhMOdR56NeNGeTcY105i5ohQ2zVy+QrgiLrDjlMfCrGGZpoQEMaCW0QHU6EbYYZICY3syhMUrPGyGpAwy/Jjyl2rtKqr/sM6RbijeX8UWvPKbAOy9fbiQ8XMncbK9dYZCmSY1INb1IObV5xzO6JalHixh3pF5Yif0NTADe0Rc9SZTnM1Rfo/i7R9N3Y+7V/WzB5zVdKeTx0zB9qd0KepZKm5tkFuCQWoD07/egCEpbcKlcOUHFq8/NrX4FlsPSGRUdSNBkHovfxycEY1hwTXhx5g3P1iVhxHRgXoMpdbA2yrHOf5qZ1VR+cYPedJJEeCeDkklIzb76qJFS8IjYeClWeL1hfQ8saEAantQy7ntA23v2rU+S5Yd44jLiQTvE7EhBABxhUqCGmTLxA5VxHujsv4jCLCyK2f32nqeg+xUNgNqnfFIsbr/MBZt0AQNLztiglEdtqXKS+IY9TE/n2Lld6rASzBfBnCW80u8h2XHEYH84jRjsc1oLXSUCKEPsXcLkSwy8nyuBBwVaaLcjS8fT5BieFwyj9bb6NVP7fkVAZdHpoD4Toepqp3VnjIOQDGsIoElzt8HmbvnSRmT4vXYDJ4NbwNycOWk02zTJxcE=
    # npm
    - secure: OkJyttuaM+LZJo7aAONdlM88LzH4l3a47urpc5RJ8aSNvHSo52NfhTHE/fV6YELtvcwxfwNs2nyH+0UzCr6hg6JqwFEU0DdygwMRWFaS9qVOmxp3vLCLb4S3hUnUBkf/s1LD2r88vvP0Yqn/o1kRoU0iR3IFf3xckjOsLMM1Q9SBPrxmBThmBv+0KM/W4diARq6XqDth5c0j7a6w2LzVn7fYZQQgnF+goO7mbupzhWm+rYKXKmUFLGAoujgoAtL/o0pIQrwqGt6fnHzCawwkbxkY3oTk4mIKfFRlo/m77Vv2ptXRAYrm0AwWaFAgyXFUMmwlS+27Lmk92izF1KFVcFu8NTE4G7Lau+BjyjOCt4HLnybQf6McVgt8StKPrA6nILpYLkMsecD0L9Tt4WHvuNCmZwQlvCD5K4bn5UJAjDRFGj8VAyl0E0bnLevH+JXJjf00ltSnOGfCb7DGJ+cyAdYtqsBd3HnCIaqj7Btzdglz1wqXA7f/+s2/xHmsBuTJKhOyHF0b3YgLk0IfhI+ZFzNwZ0U9Rrut4YTQn5xtg+YpuLQDHWeJbffldJeU+WmA6ObaqGbzEVakEaN0WPm7f91JdaiJc7QBARqS92fgtdJPU3J811+ndpAsZ1GEvwPMo+OFsQeV9d1zNDyZ1st//R4XQGD44kTwLI47XTE8cMM=
cache:
  npm: true
  directories:
    - dist
    - reports
jobs:
  include:
    - stage: prepare cache
      name: install
      before_install:
        - rm -rf dist reports
      install:
        - npm i
    - stage: website
      name: build
      script:
        # - echo $TRAVIS_PULL_REQUEST_BRANCH
        # - echo $TRAVIS_BRANCH
        # - echo $TRAVIS_COMMIT
        # - echo $TRAVIS_PULL_REQUEST_SHA
        - if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then export PT_BRANCH=$TRAVIS_BRANCH; else export PT_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi
        - if [ -z "$TRAVIS_PULL_REQUEST_SHA" ]; then export PT_COMMIT=$TRAVIS_COMMIT; else export PT_COMMIT=$TRAVIS_PULL_REQUEST_SHA; fi
        # - echo $PT_COMMIT
        # - echo $PT_BRANCH
        - npm run static --base=/nuxt-page-generator-helper/
    - stage: deploy
      if: branch = master
      install:
        - npm i semantic-release @semantic-release/exec @semantic-release/git @semantic-release/changelog --no-save
      script:
        - npx semantic-release --provider=github
        - mkdir gh-pages gh-pages/reports
        - cp -R dist/* gh-pages/
        - cp -R reports/* gh-pages/reports/
        - touch gh-pages/.nojekyll
      deploy:
        provider: pages
        cleanup: false
        github_token: $GH_TOKEN
        local_dir: gh-pages/
        on:
          branch: master
        edge: true


